### PR TITLE
release tools

### PR DESCRIPTION
**Pull request by pohly**
This imports csi-release-tools and sets up a skeleton project.

/hold

Travis CI should be enabled first.

### CODE REVIEW

**Comment by pohly** [comment]
This conflicts with PR #2. I would prefer to first get Travis CI working and merge this PR, then rebase PR #2. That way we know from the beginning that PR #2 passes all checks. It also has the slight advantage that I don't need to touch any of the driver code :wink:

But we can also do it the other way around.

**Comment by mathu97** [comment]
@pohly this sounds good

**Comment by msau42** [comment]
travis and quay setup

**Comment by pohly** [comment]
https://travis-ci.org/kubernetes-csi/csi-driver-fibre-channel/builds/503510995 succeeded.

/hold cancel

**Comment by mathu97** [comment]
@msau42 @pohly is this good to merge?

**Comment by pohly** [comment]
I think it can be merged.

**Pull request merged**
